Update Readme - contrib and install
AnonymousDapper/aiotnb pull request #9
Opened 2021-06-17 05:53 UTC by Aareon

Add pytest info
Add installation in develop-mode info

Add regular installation info

2021-06-25 01:10 UTC, AnonymousDapper requested changes
I like the readme changes, but I want to keep the other code separate for now. Feel free to merge after addressing the other comments.

2021-06-25 01:10 UTC, AnonymousDapper commented on setup.py
> +
Remove this for now, let's keep the backport issue in the other PR.

2021-06-25 01:10 UTC, AnonymousDapper commented on setup.py
> +    python_requires=">=3.6.1",
Same situation as future-annotations. Remove this for now and we'll keep working on it separately.

2021-06-25 01:10 UTC, AnonymousDapper commented on README.md
> +`git clone https://github.com/AnonymousDapper/aiotnb && cd aiotnb`
Include a `git checkout bank-api` here, as it won't default to that branch.

2021-06-25 01:10 UTC, AnonymousDapper commented on setup.py
> +from sys import version_info
This also is part of the future-annotations code, so it goes.

2021-06-30 19:44 UTC, Aareon commented
Closing to fix commits. Will open a new PR.

2021-06-30 19:44 UTC, closed without merging